import data_store.enums as enums

classifiers = {
    enums.Classifier.MainComponentsAndAssemblies: "Main components and assemblies",
    enums.Classifier.Mechanisms: "Mechanisms",
    enums.Classifier.Materials: "Materials",
    enums.Classifier.Filters: "Filters",
    enums.Classifier.Liquids: "Liquids",
    enums.Classifier.Electrics: "Electrics",
}

main_components = {
    enums.MainComponent.EngineAndItsSystems: "Engine and its systems",
    enums.MainComponent.TransmissionSystem: "Transmission system",
    enums.MainComponent.Chassis: "Chassis",
    enums.MainComponent.Body: "Body",
    enums.MainComponent.Steering: "Steering",
    enums.MainComponent.BrakeSystem: "Brake system",
    enums.MainComponent.ElectricalEquipment: "Electrical equipment",
    enums.MainComponent.AdditionalEquipment: "Additional equipment",
    enums.MainComponent.Engine: "Engine",
    enums.MainComponent.PowerSystem: "Power system",
    enums.MainComponent.CoolingSystem: "Cooling system",
    enums.MainComponent.LubricationSystem: "Lubrication system",
    enums.MainComponent.ExhaustSystem: "Exhaust system",
    enums.MainComponent.Clutch: "Clutch",
    enums.MainComponent.Gearbox: "Gearbox",
    enums.MainComponent.WheelDrive: "Wheel drive",
    enums.MainComponent.FrontSuspension: "Front suspension",
    enums.MainComponent.RearSuspension: "Rear suspension",
    enums.MainComponent.Wheels: "Wheels",
    enums.MainComponent.Tires: "Tires",
    enums.MainComponent.ServiceBrakeSystem: "Service brake system",
    enums.MainComponent.ParkingBrakeSystem: "Parking brake system",
    enums.MainComponent.ElectricitySources: "Electricity sources",
    enums.MainComponent.ElectricityConsumers: "Electricity consumers",
}

widget_indexes = {
    enums.MainComponent.EngineAndItsSystems: enums.WidgetIndex.Empty,
    enums.MainComponent.TransmissionSystem: enums.WidgetIndex.Empty,
    enums.MainComponent.Chassis: enums.WidgetIndex.Empty,
    enums.MainComponent.Body: enums.WidgetIndex.Body,
    enums.MainComponent.Steering: enums.WidgetIndex.Steering,
    enums.MainComponent.BrakeSystem: enums.WidgetIndex.Empty,
    enums.MainComponent.ElectricalEquipment: enums.WidgetIndex.Empty,
    enums.MainComponent.AdditionalEquipment: enums.WidgetIndex.Empty,
    enums.MainComponent.Engine: enums.WidgetIndex.Engine,
    enums.MainComponent.PowerSystem: enums.WidgetIndex.PowerSystem,
    enums.MainComponent.CoolingSystem: enums.WidgetIndex.CoolingSystem,
    enums.MainComponent.LubricationSystem: enums.WidgetIndex.LubricationSystem,
    enums.MainComponent.ExhaustSystem: enums.WidgetIndex.ExhaustSystem,
    enums.MainComponent.Clutch: enums.WidgetIndex.Clutch,
    enums.MainComponent.Gearbox: enums.WidgetIndex.Gearbox,
    enums.MainComponent.WheelDrive: enums.WidgetIndex.WheelDrive,
    enums.MainComponent.FrontSuspension: enums.WidgetIndex.FrontSuspension,
    enums.MainComponent.RearSuspension: enums.WidgetIndex.RearSuspension,
    enums.MainComponent.Wheels: enums.WidgetIndex.Wheels,
    enums.MainComponent.Tires: enums.WidgetIndex.Tires,
    enums.MainComponent.ServiceBrakeSystem: enums.WidgetIndex.ServiceBrakeSystem,
    enums.MainComponent.ParkingBrakeSystem: enums.WidgetIndex.ParkingBrakeSystem,
    enums.MainComponent.ElectricitySources: enums.WidgetIndex.ElectricitySources,
    enums.MainComponent.ElectricityConsumers: enums.WidgetIndex.ElectricityConsumers,
}
